//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.27 at 01:26:12 PM ICT 
//


package demo.project3.schema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="preRunProteinConsumtion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="postRunProteinConsumtion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="postRunFatConsumtion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="postRunCarbConsumtion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="runnerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="restaurantTypeInterest" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preRunProteinConsumtion",
    "postRunProteinConsumtion",
    "postRunFatConsumtion",
    "postRunCarbConsumtion",
    "runnerType",
    "restaurantTypeInterest"
})
@XmlRootElement(name = "getRestaurantRecommendationRequest")
public class GetRestaurantRecommendationRequest {

    @XmlElement(required = true)
    protected String preRunProteinConsumtion;
    @XmlElement(required = true)
    protected String postRunProteinConsumtion;
    @XmlElement(required = true)
    protected String postRunFatConsumtion;
    @XmlElement(required = true)
    protected String postRunCarbConsumtion;
    @XmlElement(required = true)
    protected String runnerType;
    @XmlElement(required = true)
    protected String restaurantTypeInterest;

    /**
     * Gets the value of the preRunProteinConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRunProteinConsumtion() {
        return preRunProteinConsumtion;
    }

    /**
     * Sets the value of the preRunProteinConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRunProteinConsumtion(String value) {
        this.preRunProteinConsumtion = value;
    }

    /**
     * Gets the value of the postRunProteinConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunProteinConsumtion() {
        return postRunProteinConsumtion;
    }

    /**
     * Sets the value of the postRunProteinConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunProteinConsumtion(String value) {
        this.postRunProteinConsumtion = value;
    }

    /**
     * Gets the value of the postRunFatConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunFatConsumtion() {
        return postRunFatConsumtion;
    }

    /**
     * Sets the value of the postRunFatConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunFatConsumtion(String value) {
        this.postRunFatConsumtion = value;
    }

    /**
     * Gets the value of the postRunCarbConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunCarbConsumtion() {
        return postRunCarbConsumtion;
    }

    /**
     * Sets the value of the postRunCarbConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunCarbConsumtion(String value) {
        this.postRunCarbConsumtion = value;
    }

    /**
     * Gets the value of the runnerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnerType() {
        return runnerType;
    }

    /**
     * Sets the value of the runnerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnerType(String value) {
        this.runnerType = value;
    }

    /**
     * Gets the value of the restaurantTypeInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestaurantTypeInterest() {
        return restaurantTypeInterest;
    }

    /**
     * Sets the value of the restaurantTypeInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestaurantTypeInterest(String value) {
        this.restaurantTypeInterest = value;
    }

}
