//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.04 at 07:26:04 PM ICT 
//


package demo.project3.schema;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="runnerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="restaurantType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="protein" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="carb" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="budgetMin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="budgetMax" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foodTypes" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="foodType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runnerType",
    "restaurantType",
    "protein",
    "fat",
    "carb",
    "budgetMin",
    "budgetMax",
    "foodTypes"
})
@XmlRootElement(name = "getRestaurantRecommendationRequest")
public class GetRestaurantRecommendationRequest {

    @XmlElement(required = true)
    protected String runnerType;
    @XmlElement(required = true)
    protected String restaurantType;
    @XmlElement(required = true)
    protected String protein;
    @XmlElement(required = true)
    protected String fat;
    @XmlElement(required = true)
    protected String carb;
    @XmlElement(required = true)
    protected String budgetMin;
    @XmlElement(required = true)
    protected String budgetMax;
    protected List<GetRestaurantRecommendationRequest.FoodTypes> foodTypes;

    /**
     * Gets the value of the runnerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnerType() {
        return runnerType;
    }

    /**
     * Sets the value of the runnerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnerType(String value) {
        this.runnerType = value;
    }

    /**
     * Gets the value of the restaurantType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestaurantType() {
        return restaurantType;
    }

    /**
     * Sets the value of the restaurantType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestaurantType(String value) {
        this.restaurantType = value;
    }

    /**
     * Gets the value of the protein property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtein() {
        return protein;
    }

    /**
     * Sets the value of the protein property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtein(String value) {
        this.protein = value;
    }

    /**
     * Gets the value of the fat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFat() {
        return fat;
    }

    /**
     * Sets the value of the fat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFat(String value) {
        this.fat = value;
    }

    /**
     * Gets the value of the carb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarb() {
        return carb;
    }

    /**
     * Sets the value of the carb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarb(String value) {
        this.carb = value;
    }

    /**
     * Gets the value of the budgetMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBudgetMin() {
        return budgetMin;
    }

    /**
     * Sets the value of the budgetMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBudgetMin(String value) {
        this.budgetMin = value;
    }

    /**
     * Gets the value of the budgetMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBudgetMax() {
        return budgetMax;
    }

    /**
     * Sets the value of the budgetMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBudgetMax(String value) {
        this.budgetMax = value;
    }

    /**
     * Gets the value of the foodTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the foodTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFoodTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetRestaurantRecommendationRequest.FoodTypes }
     * 
     * 
     */
    public List<GetRestaurantRecommendationRequest.FoodTypes> getFoodTypes() {
        if (foodTypes == null) {
            foodTypes = new ArrayList<GetRestaurantRecommendationRequest.FoodTypes>();
        }
        return this.foodTypes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="foodType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "foodType"
    })
    public static class FoodTypes {

        @XmlElement(required = true)
        protected String foodType;

        /**
         * Gets the value of the foodType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoodType() {
            return foodType;
        }

        /**
         * Sets the value of the foodType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoodType(String value) {
            this.foodType = value;
        }

    }

}
