//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.03 at 05:18:41 PM ICT 
//


package demo.project3.schema;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="district" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="raceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="typeofEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="travelPlaceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="activityArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="standard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PostRunCarbConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PostRunFatConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PostRunProteinConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreRunCarbConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreRunFatConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreRunProteinConsumtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hasRestaurantTypeInterest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RunnerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BudgetInteresets" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="BudgetInterest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hasFoodTypeInterests" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="hasFoodTypeInterest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "message",
    "username",
    "district",
    "raceType",
    "typeofEvent",
    "travelPlaceType",
    "price",
    "organization",
    "activityArea",
    "standard",
    "level",
    "startPeriod",
    "reward",
    "postRunCarbConsumtion",
    "postRunFatConsumtion",
    "postRunProteinConsumtion",
    "preRunCarbConsumtion",
    "preRunFatConsumtion",
    "preRunProteinConsumtion",
    "hasRestaurantTypeInterest",
    "runnerType",
    "budgetInteresets",
    "hasFoodTypeInterests"
})
@XmlRootElement(name = "getUserProfileResponse")
public class GetUserProfileResponse {

    protected String status;
    protected String message;
    protected String username;
    protected String district;
    protected String raceType;
    protected String typeofEvent;
    protected String travelPlaceType;
    protected String price;
    protected String organization;
    protected String activityArea;
    protected String standard;
    protected String level;
    protected String startPeriod;
    protected String reward;
    @XmlElement(name = "PostRunCarbConsumtion")
    protected String postRunCarbConsumtion;
    @XmlElement(name = "PostRunFatConsumtion")
    protected String postRunFatConsumtion;
    @XmlElement(name = "PostRunProteinConsumtion")
    protected String postRunProteinConsumtion;
    @XmlElement(name = "PreRunCarbConsumtion")
    protected String preRunCarbConsumtion;
    @XmlElement(name = "PreRunFatConsumtion")
    protected String preRunFatConsumtion;
    @XmlElement(name = "PreRunProteinConsumtion")
    protected String preRunProteinConsumtion;
    protected String hasRestaurantTypeInterest;
    @XmlElement(name = "RunnerType")
    protected String runnerType;
    @XmlElement(name = "BudgetInteresets")
    protected GetUserProfileResponse.BudgetInteresets budgetInteresets;
    protected GetUserProfileResponse.HasFoodTypeInterests hasFoodTypeInterests;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the raceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceType() {
        return raceType;
    }

    /**
     * Sets the value of the raceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceType(String value) {
        this.raceType = value;
    }

    /**
     * Gets the value of the typeofEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeofEvent() {
        return typeofEvent;
    }

    /**
     * Sets the value of the typeofEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeofEvent(String value) {
        this.typeofEvent = value;
    }

    /**
     * Gets the value of the travelPlaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravelPlaceType() {
        return travelPlaceType;
    }

    /**
     * Sets the value of the travelPlaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravelPlaceType(String value) {
        this.travelPlaceType = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the activityArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityArea() {
        return activityArea;
    }

    /**
     * Sets the value of the activityArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityArea(String value) {
        this.activityArea = value;
    }

    /**
     * Gets the value of the standard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandard() {
        return standard;
    }

    /**
     * Sets the value of the standard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandard(String value) {
        this.standard = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the startPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPeriod() {
        return startPeriod;
    }

    /**
     * Sets the value of the startPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPeriod(String value) {
        this.startPeriod = value;
    }

    /**
     * Gets the value of the reward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReward() {
        return reward;
    }

    /**
     * Sets the value of the reward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReward(String value) {
        this.reward = value;
    }

    /**
     * Gets the value of the postRunCarbConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunCarbConsumtion() {
        return postRunCarbConsumtion;
    }

    /**
     * Sets the value of the postRunCarbConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunCarbConsumtion(String value) {
        this.postRunCarbConsumtion = value;
    }

    /**
     * Gets the value of the postRunFatConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunFatConsumtion() {
        return postRunFatConsumtion;
    }

    /**
     * Sets the value of the postRunFatConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunFatConsumtion(String value) {
        this.postRunFatConsumtion = value;
    }

    /**
     * Gets the value of the postRunProteinConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunProteinConsumtion() {
        return postRunProteinConsumtion;
    }

    /**
     * Sets the value of the postRunProteinConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunProteinConsumtion(String value) {
        this.postRunProteinConsumtion = value;
    }

    /**
     * Gets the value of the preRunCarbConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRunCarbConsumtion() {
        return preRunCarbConsumtion;
    }

    /**
     * Sets the value of the preRunCarbConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRunCarbConsumtion(String value) {
        this.preRunCarbConsumtion = value;
    }

    /**
     * Gets the value of the preRunFatConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRunFatConsumtion() {
        return preRunFatConsumtion;
    }

    /**
     * Sets the value of the preRunFatConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRunFatConsumtion(String value) {
        this.preRunFatConsumtion = value;
    }

    /**
     * Gets the value of the preRunProteinConsumtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRunProteinConsumtion() {
        return preRunProteinConsumtion;
    }

    /**
     * Sets the value of the preRunProteinConsumtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRunProteinConsumtion(String value) {
        this.preRunProteinConsumtion = value;
    }

    /**
     * Gets the value of the hasRestaurantTypeInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasRestaurantTypeInterest() {
        return hasRestaurantTypeInterest;
    }

    /**
     * Sets the value of the hasRestaurantTypeInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasRestaurantTypeInterest(String value) {
        this.hasRestaurantTypeInterest = value;
    }

    /**
     * Gets the value of the runnerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnerType() {
        return runnerType;
    }

    /**
     * Sets the value of the runnerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnerType(String value) {
        this.runnerType = value;
    }

    /**
     * Gets the value of the budgetInteresets property.
     * 
     * @return
     *     possible object is
     *     {@link GetUserProfileResponse.BudgetInteresets }
     *     
     */
    public GetUserProfileResponse.BudgetInteresets getBudgetInteresets() {
        return budgetInteresets;
    }

    /**
     * Sets the value of the budgetInteresets property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetUserProfileResponse.BudgetInteresets }
     *     
     */
    public void setBudgetInteresets(GetUserProfileResponse.BudgetInteresets value) {
        this.budgetInteresets = value;
    }

    /**
     * Gets the value of the hasFoodTypeInterests property.
     * 
     * @return
     *     possible object is
     *     {@link GetUserProfileResponse.HasFoodTypeInterests }
     *     
     */
    public GetUserProfileResponse.HasFoodTypeInterests getHasFoodTypeInterests() {
        return hasFoodTypeInterests;
    }

    /**
     * Sets the value of the hasFoodTypeInterests property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetUserProfileResponse.HasFoodTypeInterests }
     *     
     */
    public void setHasFoodTypeInterests(GetUserProfileResponse.HasFoodTypeInterests value) {
        this.hasFoodTypeInterests = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BudgetInterest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "budgetInterest"
    })
    public static class BudgetInteresets {

        @XmlElement(name = "BudgetInterest")
        protected List<String> budgetInterest;

        /**
         * Gets the value of the budgetInterest property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the budgetInterest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBudgetInterest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBudgetInterest() {
            if (budgetInterest == null) {
                budgetInterest = new ArrayList<String>();
            }
            return this.budgetInterest;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="hasFoodTypeInterest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasFoodTypeInterest"
    })
    public static class HasFoodTypeInterests {

        protected List<String> hasFoodTypeInterest;

        /**
         * Gets the value of the hasFoodTypeInterest property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the hasFoodTypeInterest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHasFoodTypeInterest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getHasFoodTypeInterest() {
            if (hasFoodTypeInterest == null) {
                hasFoodTypeInterest = new ArrayList<String>();
            }
            return this.hasFoodTypeInterest;
        }

    }

}
