//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.03 at 05:18:41 PM ICT 
//


package demo.project3.schema;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo.project3.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo.project3.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllRestaurantResponse }
     * 
     */
    public GetAllRestaurantResponse createGetAllRestaurantResponse() {
        return new GetAllRestaurantResponse();
    }

    /**
     * Create an instance of {@link GetRestaurantRecommendationRequest }
     * 
     */
    public GetRestaurantRecommendationRequest createGetRestaurantRecommendationRequest() {
        return new GetRestaurantRecommendationRequest();
    }

    /**
     * Create an instance of {@link GetRestaurantRecommendationResponse }
     * 
     */
    public GetRestaurantRecommendationResponse createGetRestaurantRecommendationResponse() {
        return new GetRestaurantRecommendationResponse();
    }

    /**
     * Create an instance of {@link GetAllRecommendationRequest }
     * 
     */
    public GetAllRecommendationRequest createGetAllRecommendationRequest() {
        return new GetAllRecommendationRequest();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse }
     * 
     */
    public GetAllRecommendationResponse createGetAllRecommendationResponse() {
        return new GetAllRecommendationResponse();
    }

    /**
     * Create an instance of {@link CreateUserProfileRequest }
     * 
     */
    public CreateUserProfileRequest createCreateUserProfileRequest() {
        return new CreateUserProfileRequest();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse }
     * 
     */
    public GetUserProfileResponse createGetUserProfileResponse() {
        return new GetUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents createGetAllRecommendationResponseRunningEvents() {
        return new GetAllRecommendationResponse.RunningEvents();
    }

    /**
     * Create an instance of {@link GetAllRestaurantRequest }
     * 
     */
    public GetAllRestaurantRequest createGetAllRestaurantRequest() {
        return new GetAllRestaurantRequest();
    }

    /**
     * Create an instance of {@link GetAllRestaurantResponse.Restaurants }
     * 
     */
    public GetAllRestaurantResponse.Restaurants createGetAllRestaurantResponseRestaurants() {
        return new GetAllRestaurantResponse.Restaurants();
    }

    /**
     * Create an instance of {@link GetRestaurantRecommendationRequest.BudgetInteresets }
     * 
     */
    public GetRestaurantRecommendationRequest.BudgetInteresets createGetRestaurantRecommendationRequestBudgetInteresets() {
        return new GetRestaurantRecommendationRequest.BudgetInteresets();
    }

    /**
     * Create an instance of {@link GetRestaurantRecommendationRequest.HasFoodTypeInterests }
     * 
     */
    public GetRestaurantRecommendationRequest.HasFoodTypeInterests createGetRestaurantRecommendationRequestHasFoodTypeInterests() {
        return new GetRestaurantRecommendationRequest.HasFoodTypeInterests();
    }

    /**
     * Create an instance of {@link GetRestaurantRecommendationResponse.Restaurants }
     * 
     */
    public GetRestaurantRecommendationResponse.Restaurants createGetRestaurantRecommendationResponseRestaurants() {
        return new GetRestaurantRecommendationResponse.Restaurants();
    }

    /**
     * Create an instance of {@link GetAllRecommendationRequest.BudgetInteresets }
     * 
     */
    public GetAllRecommendationRequest.BudgetInteresets createGetAllRecommendationRequestBudgetInteresets() {
        return new GetAllRecommendationRequest.BudgetInteresets();
    }

    /**
     * Create an instance of {@link GetAllRecommendationRequest.HasFoodTypeInterests }
     * 
     */
    public GetAllRecommendationRequest.HasFoodTypeInterests createGetAllRecommendationRequestHasFoodTypeInterests() {
        return new GetAllRecommendationRequest.HasFoodTypeInterests();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.Restaurants }
     * 
     */
    public GetAllRecommendationResponse.Restaurants createGetAllRecommendationResponseRestaurants() {
        return new GetAllRecommendationResponse.Restaurants();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.TravelPlaces }
     * 
     */
    public GetAllRecommendationResponse.TravelPlaces createGetAllRecommendationResponseTravelPlaces() {
        return new GetAllRecommendationResponse.TravelPlaces();
    }

    /**
     * Create an instance of {@link CreateUserProfileRequest.BudgetInteresets }
     * 
     */
    public CreateUserProfileRequest.BudgetInteresets createCreateUserProfileRequestBudgetInteresets() {
        return new CreateUserProfileRequest.BudgetInteresets();
    }

    /**
     * Create an instance of {@link CreateUserProfileRequest.HasFoodTypeInterests }
     * 
     */
    public CreateUserProfileRequest.HasFoodTypeInterests createCreateUserProfileRequestHasFoodTypeInterests() {
        return new CreateUserProfileRequest.HasFoodTypeInterests();
    }

    /**
     * Create an instance of {@link CreateUserProfileResponse }
     * 
     */
    public CreateUserProfileResponse createCreateUserProfileResponse() {
        return new CreateUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetUserProfileRequest }
     * 
     */
    public GetUserProfileRequest createGetUserProfileRequest() {
        return new GetUserProfileRequest();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.BudgetInteresets }
     * 
     */
    public GetUserProfileResponse.BudgetInteresets createGetUserProfileResponseBudgetInteresets() {
        return new GetUserProfileResponse.BudgetInteresets();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.HasFoodTypeInterests }
     * 
     */
    public GetUserProfileResponse.HasFoodTypeInterests createGetUserProfileResponseHasFoodTypeInterests() {
        return new GetUserProfileResponse.HasFoodTypeInterests();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.RaceTypes }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.RaceTypes createGetAllRecommendationResponseRunningEventsRaceTypes() {
        return new GetAllRecommendationResponse.RunningEvents.RaceTypes();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.Prices }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.Prices createGetAllRecommendationResponseRunningEventsPrices() {
        return new GetAllRecommendationResponse.RunningEvents.Prices();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.StartPeriods }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.StartPeriods createGetAllRecommendationResponseRunningEventsStartPeriods() {
        return new GetAllRecommendationResponse.RunningEvents.StartPeriods();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.ActivityAreas }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.ActivityAreas createGetAllRecommendationResponseRunningEventsActivityAreas() {
        return new GetAllRecommendationResponse.RunningEvents.ActivityAreas();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.Rewards }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.Rewards createGetAllRecommendationResponseRunningEventsRewards() {
        return new GetAllRecommendationResponse.RunningEvents.Rewards();
    }

    /**
     * Create an instance of {@link GetAllRecommendationResponse.RunningEvents.TravelPlacesRunning }
     * 
     */
    public GetAllRecommendationResponse.RunningEvents.TravelPlacesRunning createGetAllRecommendationResponseRunningEventsTravelPlacesRunning() {
        return new GetAllRecommendationResponse.RunningEvents.TravelPlacesRunning();
    }

}
