//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.05 at 04:17:15 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://project3.demo/schema")
package demo.project3.schema;
