//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.27 at 06:39:51 AM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://project3.demo/schema")
package demo.project3.schema;
